apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Dev
  type: core.Directory
  children:
  - name: core.dev
    type: udm.Environment
    members:
    - Infrastructure/Windows/win2012r2-dev/testrunner
    - Infrastructure/Windows/win2012r2-dev
    - Infrastructure/Windows/win2012r2-dev/sql.server
    dictionaries:
    - Environments/Dev/Dict/Dict-core-dev
  - directory: Dict
    children:
    - name: Dict-core-dev
      type: udm.Dictionary
      entries:
        TIMEOUT: "1000"
        listen.port: "8080"
        suffix: dev
        TITLE: Dogs and Cats
        alternate.color: blue

