#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("helpers.star","app","config","secret","env")
#@ load("helpers.lib.yml", "encoded_entries")

#@ for container in data.values.containers:
#@ if hasattr(container,"secret"):
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ secret(container)
type: Opaque
data: #@ encoded_entries(container.secret)['entries']
#@ end
#@ end

#@ for container in data.values.containers:
#@ if hasattr(container,"config"):
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ config(container)
data: #@ container.config
#@ end
#@ end