#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("helpers.star","app","config","secret","env","encoded_entries","ns")
#@ load("helpers.lib.yml", "labels")

#@ for container in data.values.containers:
#@ if hasattr(container,"secret"):
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ secret(container)
  labels: #@ labels(container)
  namespace: #@ ns(data.values.environment)
type: Opaque
data: #@ encoded_entries(container.secret)
#@ end
#@ end

#@ for container in data.values.containers:
#@ if hasattr(container,"config"):
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ config(container)
  labels: #@ labels(container)
  namespace: #@ ns(data.values.environment)
data: #@ container.config
#@ end
#@ end
