apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pets-ingress  
  namespace: canary
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`pets.canary.pet-cluster.demo`)
    kind: Rule
    services:
    - name: pets-app-v2
      port: 9000
      strategy: RoundRobin
      weight: 80
    - name: pets-app-v3
      port: 9000    
      strategy: RoundRobin
      weight: 20
