apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: .NET
  type: core.Directory
  children:
  - name: services
    type: core.Directory
    children:
    - name: dogs
      type: udm.Application
      children:
      - name: !value version
        type: udm.DeploymentPackage
        deployables:
        - name: dog-sql
          type: sql.SqlScripts
          file: !file sql
        - name: dog
          type: file.Folder
          targetPath: C:\SERVICES\{{env}}\DOGS
          createTargetPath: True
          file: !file "."
        - name: dog-service
          type: windows.ServiceSpec
          serviceName: dogService{{env}}
          serviceDisplayName: MicroPet-{{env}} Dog Service
          serviceDescription: The core dog service
          binaryPathName: C:\SERVICES\{{env}}\DOGS\dog.exe
        - name: test dog service
          type: smoketest.HttpRequestTest
          url: http://localhost:{{dogs.listen.port}}
          expectedResponseText: Total
        orchestrator:
          - sequential-by-deployment-group

