apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gui
  labels:
    app.tanzu.vmware.com/workload-type: micropet-gui-service
spec:
  source:
    git:
      url: https://github.com/bmoussaud/micropets-app/
      ref:
        branch: master
  params:
    - name: broker_service
      value: "http://front.mytanzu.xyz/pets/v1"    
    - name: observability
      value: true
  
