apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Containers
  type: core.Directory
  children:
  - name: micropets
    type: core.Directory
    children:
    - name: gui
      type: udm.Application
      children:
      - name: !value version
        type: udm.DeploymentPackage
        orchestrator:
        - sequential-by-deployed
        deployables:
        - name: gui
          type: uccm.ContainerSpec
          image: !format localhost:5000/gui:%version%
          replicas: "1"
          profile: production
          ports:
          - name: web
            type: uccm.ContainerPortSpec
            containerPort: "80"
            exposeAsService: True
            servicePort: "80" 
            exposeAsIngress: True
          mountedFiles:
          - name: configuration 
            type: uccm.MountedFileSpec
            path: /usr/share/nginx/html/assets/config
            isSensitive: False
            file: !file "./delivery/config.json"
        - name: test gui service availability
          type: smoketest.HttpRequestTest
          url: http://micropet.k8s.{{env}}.gui.xebialabs.demo
          expectedResponseText: Gui

