apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: .NET
  type: core.Directory
  children:
  - name: services
    type: core.Directory
    children:
    - name: cats
      type: udm.Application
      children:
      - name: !value version
        type: udm.DeploymentPackage
        deployables:
        - name: cat-sql
          type: sql.SqlScripts
          file: !file sql
        - name: cat
          type: file.Folder
          targetPath: C:\SERVICES\{{env}}\CATS
          createTargetPath: True
          file: !file "."
        - name: cat-service
          type: windows.ServiceSpec
          serviceName: catService{{env}}
          serviceDisplayName: MicroPet-{{env}} Cat Service
          serviceDescription: The core cat service
          binaryPathName: C:\SERVICES\{{env}}\CATS\cat.exe
        - name: test cat service
          type: smoketest.HttpRequestTest
          url: http://localhost:{{cats.listen.port}}
          expectedResponseText: Total
        orchestrator:
          - sequential-by-deployment-group

