---
apiVersion: v1
kind: Secret
metadata:
  name: dogs-db-credentials
type: Opaque
data:
  user: YWRtaW4K
  password: cGxlYXNlY2hhbmdlbWU=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dogs-config
data:
  config.properties: |
    listen.port: 7003
---
kind: Deployment
apiVersion: apps/v1
metadata:  
  name: dogs-app
  labels:
    app: dogs-app
    group: micro-pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogs-app
      group: micro-pet
  template:
    metadata:
      labels:
        app: dogs-app
        group: micro-pet
    spec:
      containers:
        - name: dogs
          image: localregistry:5000/micropet/dogs:dev
          imagePullPolicy: Always
          ports:
            - name: dogs
              containerPort: 7003
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://dogs-db:5432/dogs
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: dogs-db-credentials
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dogs-db-credentials
                  key: password

      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dogs-service
  labels:
    app: dogs-app
    group: micro-pet
spec:
  ports:
    - protocol: TCP
      name: dogs
      port: 7003
  selector:
    app: dogs-app
    group: micro-pet
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: dogs-ingress    
spec:
  rules:
    - host: k8s.mytanzu.xyz
      http:
        paths:
          - path: /dogs
            backend:
              serviceName: dogs-service
              servicePort: 7003         






