apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: sample-dogs
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://github.com/bmoussaud/micropets-app
        ref: master
        subPath: cluster/tap/app-operator/kapp
  template:
    - ytt:
        ignoreUnknownComments: true
        #valuesFrom:
        #  - configMapRef:
        #      name: cfgmap-name        
  deploy:
    - kapp: {}