apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Containers
  type: core.Directory
  children:
  - name: micropets
    type: core.Directory
    children:
    - name: pets-py
      type: udm.Application
      children:
      - name: !value version
        type: udm.DeploymentPackage
        orchestrator:
        - sequential-by-deployed
        deployables:
        - name: petspy
          type: uccm.ContainerSpec
          image: !format localhost:5000/petspy:%imageversion%
          replicas: "1"
          profile: production
          env:
            SERVICE: cats-web-service                        
          ports:
          - name: web
            type: uccm.ContainerPortSpec
            containerPort: "7009"
            exposeAsService: True
            servicePort: "80" 
            exposeAsIngress: True          
        - name: test pets-py service availability
          type: smoketest.HttpRequestTest
          url: http://micropet.k8s.{{env}}.pets-py.xebialabs.demo/pets
          expectedResponseText: status

