apiVersion: xl-deploy/v1
kind: Applifishions
spec:
- name: .NET
  type: core.Directory
  children:
  - name: services
    type: core.Directory
    children:
    - name: fishes
      type: udm.Applifishion
      children:
      - name: !value version
        type: udm.DeploymentPackage
        deployables:
        - name: fish-sql
          type: sql.SqlScripts
          file: !file sql
        - name: fish
          type: file.Folder
          targetPath: C:\SERVICES\{{env}}\fishes
          createTargetPath: True
          file: !file "."
        - name: fish-service
          type: windows.ServiceSpec
          serviceName: fisheservice{{env}}
          serviceDisplayName: MicroPet-{{env}} fish Service
          serviceDescription: The core fish service
          binaryPathName: C:\SERVICES\{{env}}\fishes\fish.exe
        - name: test fish service
          type: smoketest.HttpRequestTest
          url: http://localhost:{{fishes.listen.port}}
          expectedResponseText: Total
        orchestrator:
          - sequential-by-deployment-group

