apiVersion: v1
kind: Pod
metadata:
  name: vegeta-pod-runner
  labels:
    run: vegeta
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: httpd
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80
  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo HTTP VEGETA RUNNER > /pod-data/index.html"]
  - name: vegeta-container
    image: bmoussaud/micropet_vegeta_runner:dev
    imagePullPolicy: Always
    volumeMounts:
    - name: shared-data
      mountPath: /vegeta-data 
    env:
    - name: MAX_LOOP
      value: "50000"
    - name: VEGETA_DURATION
      value: "60s"    
    - name: VEGETA_RATE
      value: "120"
---
apiVersion: v1
kind: Service
metadata:
  name: vegeta-service
  labels:
    run: vegeta
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: vegeta

