# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources-dev.yaml
namespace: micropetdev
images:
  - name: localregistry:5000/micropet/cats
    newName: bmoussaud/micropet_cats