---
kind: Deployment
apiVersion: apps/v1
metadata:  
  name: pets-config-server-app
  labels:
    app: pets-config-server-app
    group: micro-pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets-config-server-app
      group: micro-pet
  template:
    metadata:
      labels:
        app: pets-config-server-app
        group: micro-pet
    spec:
      containers:
        - name: pets-config
          image: localregistry:5000/pets/config-server:latest
          imagePullPolicy: Always
          env:
          - name: SPRING_SECURITY_USER_NAME
            value: scott
          - name: SPRING_SECURITY_USER_PASSWORD
            value: tiger
          - name: SPRING_PROFILES_ACTIVE
            value: docker,git
          ports:
            - containerPort: 8888
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pets-config-server-service
  labels:
    app: pets-config-server-app
    group: micro-pet
spec:
  ports:
    - protocol: TCP      
      port: 8888
  selector:
    app: pets-config-server-app
    group: micro-pet
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pets-config-server-ingress  
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`pets-config-server.dev.pet-cluster.demo`)
    kind: Rule
    services:
    - name: pets-config-server-service
      port: 8888
