
apiVersion: xl-deploy/v1
kind: Deployment
spec:
  package: !format "Applications/.NET/services/pets/%version%"
  environment: Environments/MicroPet/Dev/micropet.dev
  onSuccessPolicy: ARCHIVE
  orchestrator:
  - sequential-by-dependency

  

