apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: .NET
  type: core.Directory
  children:
  - name: services
    type: core.Directory
    children:
    - name: pets
      type: udm.Application
      children:
      - name: !value version
        type: udm.DeploymentPackage
        deployables:
        - name: pet
          type: file.Folder
          targetPath: C:\SERVICES\{{env}}\PETS
          createTargetPath: True
          file: !file "."
        - name: pet-service
          type: windows.ServiceSpec
          serviceName: petService{{env}}
          serviceDisplayName: MicroPet-{{env}} Pet Service
          serviceDescription: The core Pet service
          binaryPathName: C:\SERVICES\{{env}}\PETS\pets.exe
        - name: test pets service
          type: smoketest.HttpRequestTest
          url: http://localhost:{{pets.listen.port}}
          expectedResponseText: Total
          #applicationDependencies:
          #dogs: '[1.0.0,2.0.0)'
          #cats: '[1.0.0,2.0.0)'          
        orchestrator:
        - parallel-by-deployment-group

