apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Containers
  type: core.Directory
  children:
  - name: micropets
    type: core.Directory
    children:
    - name: pets
      type: udm.Application
      children:
      - name: !value version
        type: udm.DeploymentPackage
        orchestrator:
        - sequential-by-deployed
        deployables:
        - name: pets
          type: uccm.ContainerSpec
          image: !format localhost:5000/pets:%version%
          replicas: "1"
          profile: production
          env:
            SERVICE_CONFIG: /etc/service/pets_config.json            
          ports:
          - name: web
            type: uccm.ContainerPortSpec
            containerPort: "7004"
            exposeAsService: True
            servicePort: "80" 
            exposeAsIngress: True
          mountedFiles:
          - name: configuration 
            type: uccm.MountedFileSpec
            path: /etc/service
            isSensitive: False
            file: !file "./delivery/pets_config.json"
        - name: test pets service availability
          type: smoketest.HttpRequestTest
          url: http://micropet.k8s.{{env}}.pets.xebialabs.demo
          expectedResponseText: Total

