#@data/values
---
application: micro-pet
version: 1.0.0
environment:
  name: test
  namespace: uat
containers:
  - name: cats
    image: registry.local:5000/micropet/cats:dev
    replicas: 1
    profile: demo
    env:
      DATABASE_URL: jdbc:postgresql://cats-db:5432/cats
    config:
      DATABASE_USER: scott
      CATS_SERVICE_LVEL: ERROR
    secret:
      DATABASE_PASSWORD: tiger
    ports:
      - name: web
        containerPort: 7002
  - name: dogs
    image: registry.local:5000/micropet/dogs:dev
    replicas: 1
    profile: demo
    ports:
      - name: web
        containerPort: 7003
  - name: fishes
    image: registry.local:5000/micropet/fishes:dev
    replicas: 1
    profile: demo
    env:
      DATABASE_URL: jdbc:postgresql://fishes-db:5432/fishes
    ports:
      - name: web
        containerPort: 7007
  - name: pets
    image: registry.local:5000/micropet/pets:dev
    replicas: 1
    profile: demo
    configfile: 
      name: pets_config.json
      file: pets_config.json
      mountedAs: /etc/service/
    env:
      SERVICE_CONFIG: /etc/service/pets_config.json 
    ports:
      - name: web
        containerPort: 9000
  - name: gui
    image: registry.local:5000/micropet/gui:dev
    replicas: 1
    profile: demo
    configfile:
      name: config.json
      file: config.json
      mountedAs: /usr/share/nginx/html/assets/config  
    ports:
      - name: web
        containerPort: 80
