---
apiVersion: v1
kind: Secret
metadata:
  name: fishes-db-credentials
type: Opaque
data:
  user: YWRtaW4K
  password: cGxlYXNlY2hhbmdlbWU=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fishes-config
data:
  config.properties: |
    listen.port: 7007
---
kind: Deployment
apiVersion: apps/v1
metadata:  
  name: fishes-app
  labels:
    app: fishes-app
    group: micro-pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishes-app
      group: micro-pet
  template:
    metadata:
      labels:
        app: fishes-app
        group: micro-pet
    spec:
      containers:
        - name: fishes
          image: registry.local:5000/micropet/fishes:dev
          ports:
            - name: fishes
              containerPort: 7007
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://fishes-db:5432/fishes
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: fishes-db-credentials
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fishes-db-credentials
                  key: password

      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fishes-service
  labels:
    app: fishes-app
    group: micro-pet
spec:
  ports:
    - protocol: TCP
      name: fishes
      port: 7007
  selector:
    app: fishes-app
    group: micro-pet
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fishes-ingress  
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`fishes.dev.pet-cluster.demo`)
    kind: Rule
    services:
    - name: fishes-service
      port: 7007



