# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../cats/k8s
- ../../dogs/k8s
- ../../fishes/k8s
- ../../gui/k8s
- ../../pets/k8s
namespace: prod
commonLabels:  
  environment: prod
patches:
- target:    
    name: cats-ingress  
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`cats.prod.pet-cluster.demo`)
- target:    
    name: dogs-ingress  
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`dogs.prod.pet-cluster.demo`)
- target:    
    name: fishes-ingress  
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`fishes.prod.pet-cluster.demo`)
- target:    
    name: gui-ingress  
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`gui.prod.pet-cluster.demo`)
- target:    
    name: pets-ingress  
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`pets.prod.pet-cluster.demo`)